app_homepage:
    pattern:  /
    defaults: { _controller: AppBundle:Default:index }

product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix:   /product
user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user

security:
    resource: "@AppBundle/Resources/config/routing/security.yml"
